obj-$(CONFIG_BT_RTL8822CE) += rtk_btusb.o
rtk_btusb-y = rtk_coex.o rtk_misc.o rtk_bt.o

#all:
#	$(MAKE) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KDIR) M=$(PWD) modules

#clean:
#	rm -rf *.o *.mod.c *.mod.o *.ko *.symvers *.order *.a
